# Generated by Django 4.2.2 on 2024-01-23 06:10
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/post/')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='image/post/')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='image/post/')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='image/post/')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='image/post/')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='image/post/')),
                ('img_6', models.ImageField(blank=True, null=True, upload_to='image/post/')),
                ('img_7', models.ImageField(blank=True, null=True, upload_to='image/post/')),
                ('img_8', models.ImageField(blank=True, null=True, upload_to='image/post/')),
                ('img_9', models.ImageField(blank=True, null=True, upload_to='image/post/')),
                ('img_10', models.ImageField(blank=True, null=True, upload_to='image/post/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))
            ],
        ),
    ]
