# Generated by Django 4.2.2 on 2024-04-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_postviews_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/posts/'),
        ),
    ]
