version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis

  mysql:
    platform: linux/x86_64
    image: mysql
    container_name: db
    hostname: mysql
    volumes:
       - /var/BarberShopDB/:/var/lib/mysql
    environment:
       MYSQL_USER: mysql
       MYSQL_ROOT_PASSWORD: UfjBRFbvIFbOIJ2
       MYSQL_PASSWORD: UfjBRFbvIFbOIJ2
       MYSQL_DATABASE: django

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /var/static:/static


  backend:
    build:
      context: .
    container_name: backend
    hostname: backend
    volumes:
      - /var/media:/app/media

    environment:
       SECRET_KEY: NFNBmbkmmgm5tGCYFYGth4ggnengwg5gg424t51455gncmxmddkjgsauwyhbvgxhsbhj
       DB_HOST: mysql
       DB_USER: root
       DB_NAME: django
       DB_PASS: UfjBRFbvIFbOIJ2
       DB_PORT: 3306
       DEBUG: False
       KAVENEGAR_API_KEY: dboiosdoidio
       CELERY_BROKER_URL: redis://redis:6379
       C_FORCE_ROOT: True

    command: >
        sh -c "python manage.py migrate && gunicorn core.wsgi:application -w 12 -b 0.0.0.0:8000 && celery -A core worker -l INFO -E"
    

    depends_on:
      - nginx
      - redis
      - mysql
