# Generated by Django 4.2.2 on 2024-11-26 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(blank=True, upload_to='products')),
                ('file2', models.FileField(blank=True, upload_to='products')),
                ('file3', models.FileField(blank=True, upload_to='products')),
                ('file4', models.FileField(blank=True, upload_to='products')),
                ('file5', models.FileField(blank=True, upload_to='products')),
                ('file6', models.FileField(blank=True, upload_to='products')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[(1, 'machine'), (2, 'kif vasayel'), (3, 'arayeshi_behdashti')], max_length=50)),
                ('price', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=1)),
                ('is_done', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
