# Generated by Django 4.2.2 on 2024-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'machine'), (2, 'kif vasayel'), (3, 'arayeshi behdashti')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='file1',
            field=models.FileField(blank=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file2',
            field=models.FileField(blank=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file3',
            field=models.FileField(blank=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file4',
            field=models.FileField(blank=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file5',
            field=models.FileField(blank=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file6',
            field=models.FileField(blank=True, upload_to='products'),
        ),
    ]
