# Generated by Django 4.2.2 on 2024-05-12 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('contact', models.CharField(choices=[('فید', 'فید'), ('هیر کات مدرن', 'هیر کات مدرن'), ('پاکسازی', 'پاکسازی'), ('پاکسازی و استایل', 'پاکسازی و استایل'), ('فید و پاکسازی', 'فید و پاکسازی'), ('فید و هریکات', 'فید و هریکات'), ('فید و میکاپ', 'فید و میکاپ'), ('فید و پاکسازی و میکاپ', 'فید و پاکسازی و میکاپ'), ('فید و استایل و میکاپ', 'فید و استایل و میکاپ'), ('فید و استایل و پاکسازی', 'فید و استایل و پاکسازی'), ('فید و استایل و میکاپ و پاکسازی', 'فید و استایل و میکاپ و پاکسازی')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
