# Generated by Django 4.2.2 on 2024-01-24 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('content', models.CharField(choices=[(1, 'فید'), (2, 'هیر کات مدرن'), (3, 'پاکسازی'), (4, 'پاکسازی و استایل'), (5, 'فید و پاکسازی'), (6, 'فید و هریکات'), (7, 'فید و میکاپ'), (8, 'فید و پاکسازی و میکاپ'), (9, 'فید و استایل و میکاپ'), (10, 'فید و استایل و پاکسازی'), (11, 'فید و استایل و میکاپ و پاکسازی')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
